apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-payment-deployment
spec:
  selector:
    matchLabels:
      app: worker-payment-pod
  template:
    metadata:
      labels:
        app: worker-payment-pod
    spec:
      containers:
        - name: worker-payment-container
          image: # valor será incluido no pipeline
          envFrom: # Use envFrom to load from ConfigMap and Secret
            - secretRef:
                name: worker-payment-secret
            - configMapRef:
                name: worker-payment-configmap

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "196Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
        
