name: Build and Deploy

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Define a variable for the solution path
    - name: Set Solution Path
      id: set_solution_path
      run: |
        # Informar aqui o caminho para o arquivo da solution
        SOLUTION_PATH="./src/WorkerServiceSolution.sln"
        echo "SOLUTION_PATH=$SOLUTION_PATH" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH

    - name: Build
      run: dotnet build $SOLUTION_PATH --configuration Release

    - name: Test
      run: dotnet test $SOLUTION_PATH --configuration Release --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=../TestResults.trx"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./CoverageReport -reporttypes:Html

    - name: Extract Coverage Percentage
      id: coverage
      run: |
        # Install xmllint if not already installed
        sudo apt-get update
        sudo apt-get install -y libxml2-utils bc

        # Find the coverage file
        coverage_file=$(find . -name "coverage.cobertura.xml" -type f -print -quit)
        if [ -z "$coverage_file" ]; then
          echo "Coverage file not found!"
          exit 1
        fi
        echo "Coverage file found: $coverage_file"

        # Extract the 'line-rate' attribute from the root <coverage> element
        coverage_percentage=$(xmllint --xpath "string(/coverage/@line-rate)" "$coverage_file")
        if [ -z "$coverage_percentage" ]; then
          echo "Failed to extract coverage percentage!"
          exit 1
        fi
        echo "Raw Coverage Percentage: $coverage_percentage"
        coverage_percentage=$(echo "$coverage_percentage * 100" | bc -l)
        coverage_percentage=$(printf "%.2f" "$coverage_percentage")
        echo "Coverage Percentage: $coverage_percentage%"
        echo "coverage_percentage=$coverage_percentage" >> $GITHUB_OUTPUT

    - name: Print Coverage Percentage
      run: |
        echo "Coverage Percentage: ${{ steps.coverage.outputs.coverage_percentage }}%"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecr-${{ vars.PROJECT_NAME }}-worker-payment
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f src/WorkerService/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src/WorkerService
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubectl
        run: |
          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
      
      - name: Create/Update Secrets
        env:
          DB_INSTANCE_PEDIDOS: ${{ secrets.DB_INSTANCE_PEDIDOS }}
          DB_PASSWORD_PEDIDOS: ${{ secrets.DB_PASSWORD_PEDIDOS }}
          DB_UID_PEDIDOS: ${{ secrets.DB_UID_PEDIDOS }}
          DB_PORT: ${{ vars.DB_PORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          SECRET_NAME="worker-payment-secret"
          CONNECTION_STRING="Server=${{ env.DB_INSTANCE_PEDIDOS }},${{ env.DB_PORT }};Database=SnackTechProductsDb;User=${{ env.DB_UID_PEDIDOS }};Password=${{ env.DB_PASSWORD_PEDIDOS }};TrustServerCertificate=True"
      
          if kubectl get secret "$SECRET_NAME" > /dev/null 2>&1; then
            kubectl delete secret "$SECRET_NAME" 
          fi
      
          kubectl create secret generic "$SECRET_NAME"  \
            --from-literal=ConnectionStrings__DatabaseConnection="$CONNECTION_STRING" \
            --from-literal=AWS__AccessKey="$AWS_ACCESS_KEY_ID" \
            --from-literal=AWS__SecretKey="$AWS_SECRET_ACCESS_KEY"
    
      - name: Create/Update configmap
        env:
          AWS_REGION: ${{ vars.AWS_REGION }} 
          SQS_QUEUE_PAYMENT_NAME: ${{ vars.SQS_QUEUE_PAYMENT_NAME }} 
          SQS_QUEUE_PAYMENT_DLQ_NAME: ${{ vars.SQS_QUEUE_PAYMENT_DLQ_NAME }}
          AWS_ACCOUNT_ID_VOCLABS: ${{ secrets.AWS_ACCOUNT_ID_VOCLABS }}

        run: |
          CONFIGMAP_NAME="worker-payment-configmap" 

          if kubectl get configmap "$CONFIGMAP_NAME" > /dev/null 2>&1; then
            kubectl delete configmap "$CONFIGMAP_NAME"
          fi

          kubectl create configmap "$CONFIGMAP_NAME" \
            --from-literal=AWS__QueueUrl="https://sqs.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ACCOUNT_ID_VOCLABS }}/${{ env.SQS_QUEUE_PAYMENT_NAME }}" \
            --from-literal=AWS__DlqQueueURL="https://sqs.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ACCOUNT_ID_VOCLABS }}/${{ env.SQS_QUEUE_PAYMENT_DLQ_NAME }}" \
            --from-literal=AWS__ServiceUrl="https://sqs.${{ env.AWS_REGION }}.amazonaws.com" 
          
      - name: Replace ECR image string value
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
        run: |
          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i k8s/01-payment-worker-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
      
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s